# Generated by Django 5.2.14 on 2026-05-26 15:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre descriptivo del partido', max_length=250)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('kick_off', models.DateTimeField(help_text='Fecha y hora de inicio del partido')),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En Vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], default='programado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kick_off'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Resultado Final (1X2)', max_length=100)),
                ('code', models.CharField(default='1X2', max_length=20)),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('suspendido', 'Suspendido'), ('cerrado', 'Cerrado'), ('liquidado', 'Liquidado')], default='abierto', max_length=20)),
                ('operator_margin', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), help_text='Margen de ganancia de la casa (ej: 0.0500 para 5%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Gana Local, Empate, Gana Visitante', max_length=50)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('result', models.CharField(choices=[('pendiente', 'Pendiente'), ('ganador', 'Ganador'), ('perdedor', 'Perdedor'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='events.market')),
            ],
        ),
        migrations.CreateModel(
            name='OddsAuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('new_odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='events.selection')),
            ],
            options={
                'verbose_name': 'Auditoría de Cuota',
                'verbose_name_plural': 'Auditoría de Cuotas',
                'ordering': ['-modified_at'],
            },
        ),
    ]
