# Generated by Django 5.2.14 on 2026-05-26 18:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='operator_margin',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5),
        ),
    ]
