# Generated by Django 5.2.14 on 2026-05-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('verification_digit', models.CharField(max_length=1)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('pendiente_verificacion', 'Pendiente de Verificación'), ('verificado', 'Verificado'), ('bloqueado', 'Bloqueado'), ('autoexcluido', 'Autoexcluido')], default='pendiente_verificacion', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
