services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: fairbet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True

  # NUEVO: Trabajador de Celery que ejecuta las tareas asíncronas
  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True

  # NUEVO: Celery Beat (El reloj/cron que programa las tareas cada X tiempo)
  celery-beat:
    build: .
    command: celery -A config beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - celery
    environment:
      - DEBUG=True

volumes:
  postgres_data: