# Generated by Django 5.2.14 on 2026-05-26 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', models.CharField(choices=[('accepted', 'Aceptada'), ('won', 'Ganada'), ('lost', 'Perdida'), ('canceled', 'Anulada')], default='accepted', max_length=20)),
                ('transaction_id', models.UUIDField(help_text='Enlace al movimiento contable inicial de bloqueo')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='events.selection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apuesta Simple',
                'verbose_name_plural': 'Apuestas Simples',
                'ordering': ['-created_at'],
            },
        ),
    ]
