# Generated by Django 5.2.14 on 2026-05-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='selection',
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('combinada', 'Combinada')], default='simple', max_length=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='transaction_id',
            field=models.UUIDField(),
        ),
        migrations.CreateModel(
            name='BetSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('bet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='betting.bet')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_selections', to='events.selection')),
            ],
        ),
    ]
