# Generated by Django 5.2.14 on 2026-05-26 16:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoExclusionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion_date', models.DateTimeField(auto_now_add=True)),
                ('excluded_until', models.DateTimeField(blank=True, help_text='Null significa autoexclusión indefinida', null=True)),
                ('reason', models.TextField(blank=True, default='Solicitud voluntaria de juego responsable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autoexcluidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPlayLimits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_deposit_limit', models.DecimalField(decimal_places=4, default=Decimal('1000.0000'), max_digits=18)),
                ('weekly_deposit_limit', models.DecimalField(decimal_places=4, default=Decimal('5000.0000'), max_digits=18)),
                ('monthly_deposit_limit', models.DecimalField(decimal_places=4, default=Decimal('20000.0000'), max_digits=18)),
                ('pending_daily_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='play_limits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
