# Generated by Django 5.2.14 on 2026-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulatory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('payload', models.TextField()),
                ('previous_hash', models.CharField(default='', max_length=64)),
                ('current_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['id'],
            },
        ),
    ]
