# Generated by Django 5.2.14 on 2026-05-26 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(help_text='UUID que amarra los movimientos de una misma operación.')),
                ('account', models.CharField(choices=[('wallet_usuario', 'Billetera de Usuario'), ('casa', 'Cuenta de la Casa'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Cuenta de Bonos')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito (Salida)'), ('CREDIT', 'Crédito (Entrada)')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Libro Contable',
                'verbose_name_plural': 'Entradas de Libro Contable',
            },
        ),
    ]
